spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: users-service
            uri: lb://USERS-SERVICE
            predicates:
              - Path=/userService/**
          - id: enroll-service
            uri: lb://ENROLL-SERVICE
            predicates:
              - Path=/enroll/**

server:
  port: 8086
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

                

